### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by shivaansh27**
added my name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@shivaansh27 you have already created the PR previously, why are you creating the PR again and again.

if you are worrying about the branch and merge conflicts, don't worry the team will resolve it and merge your PR.

please close this PR.

please understand.

**Comment by vivekvardhan2810** [comment]
@shivaansh27 please close this PR.

**Comment by shivaansh27** [comment]
sorry, i have closed the pr

**Comment by vivekvardhan2810** [comment]
@shivaansh27 no problem, because if you create multiple PR's the team can't identify which one is open close or merged, so that's why i have said to close the PR.

i hope you got it.

now don't create another PR, because of merge conflicts.

don't worry the team will resolve it and merge your PR.

**Comment by vivekvardhan2810** [comment]
@shivaansh27 one more thing.

firstly i am not a part of the GSSOC team,

i am just an observer and reviewer, i can't merge any PR'S of postman, the team will look into your PR, they will do it.

i hope you understand.

**Comment by shivaansh27** [comment]
@vivekvardhan2810 okok i understand that currently there's only one opened pr and no worries i ain't gonna create other pr.

**Pull request closed without merging**
