### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by sanskritim2302**
Added my name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@sanskritim2302  you have already created the pull request previously, then why are you creating the PR again.

if you are worrying about the branch and merge conflicts, the team will resolve it and merge your PR.

Please close this PR.

**Comment by sanskritim2302** [comment]
Hi @vivekvardhan2810, could you please confirm if my pull request to add my name has been merged? Thank you!

**Comment by vivekvardhan2810** [comment]
@sanskritim2302 your pull request didn't merged.

Because you have closed the pull request.

Please do create another PR, and don't close that PR which you are gonna create.

**Comment by vivekvardhan2810** [comment]
@sanskritim2302 one more thing

firstly i am not a part of the GSSOC team,

i am just an observer and reviewer, i can't merge any PR'S of postman, the team will look into your PR, they will merge this.

i hope you understand.

**Comment by sanskritim2302** [comment]
Thanks for the update, @vivekvardhan2810! No problem—I’ve created a new PR (#3763), and I’m hoping the team can review it soon.

**Pull request closed without merging**
