### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by UppuluriKalyani**

### CODE REVIEW

**Review by Asymtode712 — APPROVED** [review]
Awesome! We have merged your PR, it would soon appear on leaderboard on the next server run.

**Comment by Asymtode712** [comment]
Removed the labels as #374 has been already merged

**Comment by UppuluriKalyani** [comment]
Hey @Asymtode712 for that PR #374 Points were visible after my PR was merged during one server run, but they disappeared after the subsequent server run so... I have made another pull request.
Or remove labels from that PR and add labels to this one🙂.

**Comment by Asymtode712** [comment]
@UppuluriKalyani Dont worry your points would be updated on next server run

**Comment by UppuluriKalyani** [comment]
@Asymtode712 yup, but if not please add labels to this one thanks!

**Comment by Asymtode712** [comment]
@UppuluriKalyani Yes sure

**Comment by UppuluriKalyani** [comment]
@Asymtode712 I know but I noticed that they appear in one server run and disappear in the next, even though my PR remains listed.. that's actually main issue.

**Comment by Asymtode712** [comment]
No it won't happen again, the bug is totally fixed now so no need to worry

**Comment by UppuluriKalyani** [comment]
@Asymtode712 ok🙂.

**Pull request merged**
