### PR TITLE
Add Name & Certificate link

### PR DESCRIPTION
**Pull request by sanskaarz**
Add Name & Certificate

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]
Thank you for creating the PR, The GSSOC Team will look into your PR very soon, and they will update and merge it.

Even if the merge conflicts comes, Don't worry the team will resolve the merge conflicts and they will merge your PR.

so please wait.

**Comment by sanskaarz** [comment]
Sure @vivekvardhan2810

**Review by shreyash3087 — APPROVED** [review]

**Comment by shreyash3087** [comment]
@sanskaarz Thanks for the PR and Congrats on your certification! Your scores will be updated soon.

**Comment by sanskaarz** [comment]
> @sanskaarz Thanks for the PR and Congrats on your certification! Your scores will be updated soon.

Thanks @shreyash3087 🪴❤️

**Pull request merged**
