### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by YashMall**

### CODE REVIEW

**Review by SakshamShandilya — APPROVED** [review]
Awesome you will be able to see your 500 points on the next leaderboard server run, let us know how much time you took to complete it.

**Comment by YashMall** [comment]
Hello Saksham, Thank you I will surely look into the leaderboard but here I'm not able to see my name on add your certificate table.

**Comment by sanjay-kv** [comment]
hey, we have issue in merging your PR, could you raise the PR again. Sorry for the trouble.

**Comment by YashMall** [comment]
Hello sir, the issue has been resolved. Thanks.

**Comment by YashMall** [comment]
> hey, we have issue in merging your PR, could you raise the PR again. Sorry for the trouble.

Hello sir, the issue has been resolved by Saksham, thanks.

**Comment by YashMall** [comment]
> Awesome you will be able to see your 500 points on the next leaderboard server run, let us know how much time you took to complete it.

Hello Saksham, I am not able to see my points on the LeaderBoard. Can you please see to it.

**Pull request closed without merging**
