### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Mansi-Tanwar**

### CODE REVIEW

**Comment by Mansi-Tanwar** [comment]
@vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Hi, @Mansi-Tanwar i am not a part of the GSSOC team,

i am just an observer, i can't merge any PR'S of postman, the team will look into your PR, they will merge this.

i hope you understand.

**Review by vivekvardhan2810 — APPROVED** [review]
Thank you for creating the PR, The GSSOC Team will look into your PR very soon, and they will update and merge it.

Even if the merge conflicts comes, Don't worry the team will resolve the merge conflicts and they will merge your PR.

so please wait.

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA please check and merge this PR.

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Pull request merged**
