### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by vansh-codes**
Added my certifications link  and fixed the Table also which got messes up
Name: Vansh Chaurasiya

### CODE REVIEW

**Comment by Princegupta101** [comment]
Can you make a new Pr @vansh-codes 
you maked a many changes under this Pr

**Comment by vansh-codes** [comment]
> Can you make a new Pr @vansh-codes you maked a many changes under this Pr

Sure making it now in 5minutes, can you instantly review it please

**Comment by vansh-codes** [comment]
@Princegupta101 Hii
created new PR
https://github.com/GSSoC24/Postman-Challenge/pull/274
Please review and merge before it gets merge conflicts

**Comment by Princegupta101** [comment]
Done bro

**Comment by vansh-codes** [comment]
> Done bro

Thank you so much @Princegupta101

**Pull request closed without merging**
