### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Khushalsarode**
added for khushalsarode

### CODE REVIEW

**Comment by Khushalsarode** [comment]
It's getting code conflicts. The sequence have been duplicated.

**Comment by sanjay-kv** [comment]
Awesome Work,
if you think I helped you somehow on opensource learning and postman  kindly nominate me in the below link:
my unicorn id is : sanjay-kv

you can select the reason as : how I helped you with opensource or being a PM how it helped you in doing your first commit.
This would be a good gesture and motivation for me to more towards community.
https://stars.github.com/nominate/

**Review by Princegupta101 — APPROVED** [review]
Awesome, You will see 500 points on next leaderboard server run.
Let us know how much time you took to complete the certification.

**Comment by Khushalsarode** [comment]
points not added on leaderboard?

**Comment by Asymtode712** [comment]
Removed labels as #731 was labelled

**Pull request merged**
