### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Shivamupadhyay09**
added my name

### CODE REVIEW

**Comment by aslams2020** [comment]
Hi, dont worry about the conflicts. will fix and merge it

**Comment by aslams2020** [comment]
was about to merge your last PR, but u closed it and i got error😅..so dont worry

**Review by aslams2020 — APPROVED** [review]

**Review by aslams2020 — COMMENTED** [review]
Congratulations for your certification! your scores will get reflected in next server update! ⚡

**Comment by Shivamupadhyay09** [comment]
thank you!

**Pull request merged**
