### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Mahendraish**
Mahendra Mistari

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Mahendraish please close this Pr, as one of your PR was merged.

**Comment by Mahendraish** [comment]
Sorry sir I don't know how close pr , I am following steps to merge pr you
send on mails, please you close this I didn't know how close

**Comment by vivekvardhan2810** [comment]
@Mahendraish at the down of this PR

You can see close pull request button 

Just click that

Screenshot_2024-11-08-08-59-04-01_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Mahendraish** [comment]
Sir but I can't find which pull request i close sir i am beginner and i not
more knowledge about GitHub so sir I can't able to find which pull request
i close

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA please close this PR.

**Comment by Mahendraish** [comment]
Sir i agar nahi close ki to nahi chalenga kya kyuki me brgginer hu aur muze
pata nahi konsi close karani he

**Comment by vivekvardhan2810** [comment]
@Mahendraish don't worry the team will close it

**Comment by Mahendraish** [comment]
Thank you sir, for supporting us and sorry I can't knowledge of git GitHub but you and your Compition help me to learn something and contribute something 
Thank you 🙏😊😊

**Comment by Mahendraish** [comment]
Thanks a lot.

**Comment by Mahendraish** [comment]
Sir i am not chiluka i am Mahendra Ishwar Mistari

**Comment by vivekvardhan2810** [comment]
@Mahendraish i have mentioned one of the team member to close this PR.

I hope.you understand.

**Comment by Mahendraish** [comment]
Sir my problem is solved na i not need do anything na

**Comment by vivekvardhan2810** [comment]
@Mahendraish this problem has been solved.

You No need anything.

Please understand.

**Pull request closed without merging**
