### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by sharmaastha15**

### CODE REVIEW

**Review by SakshamShandilya — APPROVED** [review]
Awesome you will be able to see your 500 points on the next leaderboard server run, let us know how much time you took to complete it.

**Comment by bharat-c27** [comment]
Hello @SakshamShandilya , I am not able to resolve conflict

**Comment by SakshamShandilya** [comment]
> Hello @SakshamShandilya , I am not able to resolve conflict

No worries I will do it before merging , tag me in your PR

**Comment by bharat-c27** [comment]
Okay Thank you so much @SakshamShandilya.
I have tag you in the PR.
PR link : #174

**Pull request merged**
