### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by aslams2020**

### CODE REVIEW

**Comment by aslams2020** [comment]
@Princegupta101

**Comment by aslams2020** [comment]
Hey @Princegupta101 
please merge the PR...It has no conflicts

**Comment by aslams2020** [comment]
@Princegupta101 PR has no conflicts..

**Review by Princegupta101 — APPROVED** [review]
Awesome you will be able to see your 500 points on the next leaderboard server run, let us know how much time you took to complete it.

**Comment by aslams2020** [comment]
@Princegupta101 Please add Postman and gssoc labels.

**Comment by aslams2020** [comment]
@SakshamShandilya Please add postman and gssoc labels

**Pull request merged**
