### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Afreen-2000**
Added my name

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
add your details at the end and number it with 2014

**Comment by Afreen-2000** [comment]
> add your details at the end and number it with 2014

okay

**Comment by AKSHITHA-CHILUKA** [comment]
also you have deleted this data 
image
so open a new pr by just adding your details at the end

**Comment by Afreen-2000** [comment]
> also you have deleted this data image so open a new pr by just adding your details at the end

**Comment by Afreen-2000** [comment]
> add your details at the end and number it with 2014

I have added at end, Can you please merge it.

**Comment by AKSHITHA-CHILUKA** [comment]
Done @Afreen-2000

**Comment by Afreen-2000** [comment]
> Done @Afreen-2000

My name is not in leaderboard?

**Comment by AKSHITHA-CHILUKA** [comment]
In the next server update you can see your details

**Comment by Afreen-2000** [comment]
> In the next server update you can see your details

Okay, Thankyou.

**Pull request closed without merging**
