### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by ikanchan**
postman challenge student expert

### CODE REVIEW

**Comment by DevBhalgamiya** [comment]
To Give Another serial number like 2470 so i can approve your pull request

**Comment by ikanchan** [comment]
What?

**Comment by DevBhalgamiya** [comment]
You have give same number 2463

**Comment by ikanchan** [comment]
okay,now I have changed it to 2470

**Review by DevBhalgamiya — APPROVED** [review]

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by ikanchan** [comment]
can this be added for hactoberfest typo if yes then how

**Comment by AKSHITHA-CHILUKA** [comment]
No hacktoberfest is over so can't add

**Pull request merged**
