### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Niraj1608**
#fix 2360

### CODE REVIEW

**Comment by Niraj1608** [comment]
@suhanipaliwal can you merge my pr

**Review by suhanipaliwal — APPROVED** [review]

**Comment by suhanipaliwal** [comment]
Your PR is merged. Points on the leaderboard will be updated shortly.

**Comment by Niraj1608** [comment]
> Your PR is merged. Points on the leaderboard will be updated shortly.

THANK YOU :)

**Comment by Yashu04** [comment]
@suhanipaliwal can you please merge my PR

**Pull request merged**
