### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by ChampGupta**
Added my name

### CODE REVIEW

**Comment by ChampGupta** [comment]
@sanjay-kv please merge the PR asap.

**Review by Mayank-joshi-21 — CHANGES_REQUESTED** [review]
Please change your serial number 2596 is my serial number otherwise you will get a conflict

**Comment by ChampGupta** [comment]
@Mayank-joshi-21 ok

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Pull request merged**
