### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by ansiace**
Added my name

### CODE REVIEW

**Comment by aslams2020** [comment]
@ansiace Please make a new PR, and don't remove existing entries. We'll Resolve them

**Comment by aslams2020** [comment]
@ansiace Also, dont worry about the conflicts may arise, we'll resolve them.

**Comment by ansiace** [comment]
@aslams2020 but i haven't remove any existing entries

**Comment by aslams2020** [comment]
Merged your new PR. your scores will get reflected in next server update! ⚡

**Pull request closed without merging**
