### PR TITLE
certificate uploaded

### PR DESCRIPTION
**Pull request by WednesdaySP**
uploaded my postman certificate

### CODE REVIEW

**Comment by WednesdaySP** [comment]
@Asymtode712 could you please merge this PR with all the required badges. Thank you

**Comment by MastanSayyad** [comment]
@WednesdaySP We can't merge it as thithis challenge is already over on 10th Aug 2024

Kindly wait till we Announce new ones

**Comment by WednesdaySP** [comment]
@MastanSayyad Thank you for the update! I understand that the challenge has ended. I'll stay tuned for the announcement of the next ones and look forward to participating then. Appreciate the clarification!

**Comment by WednesdaySP** [comment]
@RadhikaMalpani1702 can you please merge this pr i have resolved the conflicts

**Comment by WednesdaySP** [comment]
@MastanSayyad please add the required labels also

**Pull request merged**
