### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by BhavikaPachauri**
Add  postman certificate #3908

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@BhavikaPachauri please close this PR, as one of your previous PR was merged 2 days ago.

please check it.

**Comment by vivekvardhan2810** [comment]
@BhavikaPachauri and why have you added other contributor certificate link.

this is not acceptable.

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA please close this PR,

and read the above messages and please reply to that contributor.

**Comment by vivekvardhan2810** [comment]
@RadhikaMalpani1702 please take the actions.

**Comment by AKSHITHA-CHILUKA** [comment]
please upload the correct link of the certificate and open a new pr @BhavikaPachauri

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA already her PR was merged before.

**Comment by AKSHITHA-CHILUKA** [comment]
oh tag me once @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@BhavikaPachauri NO NEED TO CREATE AGAIN A NEW PR.

**Pull request closed without merging**
