### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by efshaperveen**

### CODE REVIEW

**Comment by aslams2020** [comment]
IMPORTANT 📢 : Follow the Instructions to Get the Postman Points - #4401

Please Read and do it ASAP. We have very less time to give you points.

**Comment by efshaperveen** [comment]
I did it please check it out

**Comment by aslams2020** [comment]
I cant see your new PR there. please check and tag me

**Comment by efshaperveen** [comment]
https://github.com/GSSoC24/Hack-Web3Conf/compare/main...efshaperveen:Hack-Web3Conf:main
please check it out i have added three times

**Pull request closed without merging**
