### PR TITLE
Add Certificate - Gaurav Bomble

### PR DESCRIPTION
**Pull request by Gauravtb2253**
I have added my certificate

### CODE REVIEW

**Comment by Gauravtb2253** [comment]
Hello 
Pls merge this as currently it does not have conflict

**Comment by Gauravtb2253** [comment]
As many people are creating PR there are conflicts happening in almost every PR

**Comment by Gauravtb2253** [comment]
Hello any updates

**Comment by Gauravtb2253** [comment]
Hi @MastanSayyad can you merge this pls sir

**Comment by MastanSayyad** [comment]
@Gauravtb2253 

image

**Comment by Gauravtb2253** [comment]
oh sorry
my bad

**Review by MastanSayyad — APPROVED** [review]

**Pull request merged**
