### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by 22001011062**
Added certificate of course with other details

### CODE REVIEW

**Comment by 22001011062** [comment]
Added name

**Review by aslams2020 — CHANGES_REQUESTED** [review]
Dont make changes to anywhere else entries - 
1.
image

2.
image

**Review by 22001011062 — COMMENTED** [review]
added name

**Review by aslams2020 — APPROVED** [review]
I fixed it

**Review by aslams2020 — APPROVED** [review]

**Review by aslams2020 — COMMENTED** [review]
Congratulations for your certification! your scores will get reflected in next server update! ⚡

**Pull request merged**
