### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Coding-Devil**
Added My API certificate : Gokulnath V (2246)
Thank you for the opportunity! looking forward to contribute and learn

### CODE REVIEW

**Comment by Coding-Devil** [comment]
Added my api certificate

**Review by Coding-Devil — COMMENTED** [review]
added new entry

**Comment by vivekvardhan2810** [comment]
@aditya-bhaumik please close this PR.

as you have merged one his PR's before.

**Comment by vivekvardhan2810** [comment]
@Coding-Devil please close this PR, as one your PR was merged previously.

**Pull request closed without merging**
