### PR TITLE
postman badge.md

### PR DESCRIPTION
**Pull request by divi-24**
Name -deepak gupta
LinkedIn- https://www.linkedin.com/in/deepakgupta249/
Certificate-https://api.badgr.io/public/assertions/2cRMNxVbRt-yxRIz8x6nWA?__email=divi2749@gmail.com
Role-GSSoC contributor ext

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
Could you please add your details at the end

**Comment by divi-24** [comment]
@AKSHITHA-CHILUKA  I HAVE COMMENTED MY DETAILS NOW

**Review by divi-24 — COMMENTED** [review]
I have mentioned all the details which have been asked

**Comment by AKSHITHA-CHILUKA** [comment]
add them at the end 
image
you have added at the top @divi-24

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
add to the end

**Review by divi-24 — COMMENTED** [review]
did all the changes you have asked for

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
can you please open a new pr and just add your details at the end @divi-24 
I am closing this pr , please open a new pr

**Pull request closed without merging**
