### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Rish6392**

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
change the number from 2566 to  2742

**Comment by Rish6392** [comment]
@AKSHITHA-CHILUKA I have changed the the number 2566 to 2742

**Comment by AKSHITHA-CHILUKA** [comment]
change it to 45 
I will merge it now

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr @Rish6392

**Pull request closed without merging**
