### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Mahendraish**
Mahendra Mistari

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Mahendraish please close this PR, as one of your PR was merged before.

**Comment by Mahendraish** [comment]
Sorry sir I don't know how close pr , I am following steps to merge pr you
send on mails, please you close this I didn't know how close

**Comment by Mahendraish** [comment]
I am sorry sir but I really don't know how close pr please you not accept
this because I didn't know how close

**Comment by vivekvardhan2810** [comment]
@Mahendraish at the down of this PR

You can see close pull request button

Just click that

Click close pull request button at down of this PR.

Screenshot_2024-11-08-08-59-04-01_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by Mahendraish** [comment]
Sir i am beginner so I don't Knowledge GitHub so nahi close ki to challenge kya

**Comment by Mahendraish** [comment]
Sir i not chiluka i am Mahendra Ishwar Mistari

**Comment by vivekvardhan2810** [comment]
@Mahendraish I have mentioned one of the team member to close this PR.

**Comment by Mahendraish** [comment]
Ok ok sir, sir this other name mail getting me or showing me this reason i
an asking, sir my problem is solved na ,i am not need anything na

**Comment by vivekvardhan2810** [comment]
@Mahendraish this problem has been solved.

No need.

Please understand.

**Comment by Mahendraish** [comment]
Ok thanks 🙏 for helping

**Comment by Mahendraish** [comment]
Thank for helping

**Pull request closed without merging**
