### PR TITLE
Postman Certification Aditya Kumar Singh

### PR DESCRIPTION
**Pull request by Adiaparmar**

### CODE REVIEW

**Review by Princegupta101 — APPROVED** [review]
Awesome you will be able to see your 500 points on next leaderboard server run,
let us know how much time you took to complete it.

**Comment by Adiaparmar** [comment]
I am not able to see any points on the leaderboeard of gssoc

**Comment by Adiaparmar** [comment]
> Awesome you will be able to see your 500 points on next leaderboard server run, let us know how much time you took to complete it.

I am not able to see my points on the leaderboard it is not uodated even after the server run

**Comment by Princegupta101** [comment]
Wait  for server update@Adiaparmar

**Comment by Adiaparmar** [comment]
> Wait for server update@Adiaparmar

Still not showing after the server update

**Pull request merged**
