### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by PasamTharun**
added my details

### CODE REVIEW

**Review by vivekvardhan2810 — CHANGES_REQUESTED** [review]
@PasamTharun Please don't delete older and other entries.

just add your details at the bottom.

please close this Pull request and create. another PR and just add your details at the bottom.

image

**Comment by PasamTharun** [comment]
Okay Im very sorry for that!!

**Comment by vivekvardhan2810** [comment]
No problem @PasamTharun.

i was just guiding you, how to do it. and you have done good work.

**Comment by PasamTharun** [comment]
Thanks a lot.

**Pull request closed without merging**
