### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by 23wh1a0513**
Added my name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@23wh1a0513 you have already a merged PR previously, then why have you created a new PR.

your previous PR was merged.

and we can see the postman points of yours on the leaderboard.

please check it.

**Comment by 23wh1a0513** [comment]
Actually they with different mail id we can create so i have done the course other mail id.

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA please look into this issue.

**Comment by AKSHITHA-CHILUKA** [comment]
Only 1 pr will be accepted

**Pull request closed without merging**
