### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by PasamTharun**
added my details

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]
Thank you for creating the PR, The GSSOC Team will look into your PR very soon, and they will update and merge it.

Even if the merge conflicts comes, Don't worry the team will resolve the merge conflicts and they will merge your PR.

so please wait.

**Comment by PasamTharun** [comment]
@vivekvardhan2810 Can u Please Tell Me Where Do i Need to Fill the form For
the Swags From Postman ??

**Comment by vivekvardhan2810** [comment]
@PasamTharun you can check in the official GSSOC linkedin.

there you can obtain the form link.

**Review by shreyash3087 — APPROVED** [review]

**Comment by shreyash3087** [comment]
@PasamTharun Thanks for the PR and Congrats on your certification! Your scores will be updated soon.

**Comment by PasamTharun** [comment]
Awesome, thank you so much!

**Pull request merged**
