### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by REHAN-18**

### CODE REVIEW

**Comment by REHAN-18** [comment]
@AKSHITHA-CHILUKA pls see this & merge

**Review by AKSHITHA-CHILUKA — APPROVED** [review]
great

**Comment by REHAN-18** [comment]
@AKSHITHA-CHILUKA ma'am when I get the points of this ?

**Comment by AKSHITHA-CHILUKA** [comment]
mostly tomorrow after the server run @REHAN-18

**Comment by REHAN-18** [comment]
@AKSHITHA-CHILUKA OK THANKS !!

**Pull request merged**
