### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by AKA-5**
please update it
@MastanSayyad  i have trying

### CODE REVIEW

**Comment by AKA-5** [comment]
@MastanSayyad  i am done with these conflicts i have been trying for almost 3-4 hours each time i get this conflict that i have overwritten some serial number and the remaining details are correct which i have provided only the serial number is causing the issue kindly solve it i don't understand what else to do

**Comment by MastanSayyad** [comment]
@AKA-5 

image

**Comment by AKA-5** [comment]
@MastanSayyad  do we need to add labels of gssoc-ext and postman by ourself or would you add it when you are merging it within the main branch

**Comment by MastanSayyad** [comment]
@AKA-5 we will do it

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Comment by AKA-5** [comment]
> Congratulations for your certification :octocat:
Thanks for your appreciation radhika (~anya🙃)

**Pull request merged**
