### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by RAQUEE07**
added my name

### CODE REVIEW

**Review by MastanSayyad — APPROVED** [review]

**Comment by RAQUEE07** [comment]
What can I do now please tell me in simple terms

**Comment by MastanSayyad** [comment]
@RAQUEE07 As your PR is bit late and gssoc has ended on 10th Aug 2024, you will not get 500 points on the leaderboard and gssoc certificate, but as you have completed Postman Certification you can post it on the social media and tag gssoc and postman then fill the form for postman swags, we select 25 winners for each batch.

**Comment by RAQUEE07** [comment]
Provide me the sample template of linkedin post and swags form

**Comment by MastanSayyad** [comment]
@RAQUEE07 Visit GirlScript Summer Of Code LinkedIn handle. You can find there.

**Comment by RAQUEE07** [comment]
Thanks, I'll check it out.

**Pull request merged**
