### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Saaarthak0102**
Add my name

### CODE REVIEW

**Review by MastanSayyad — APPROVED** [review]

**Review by MastanSayyad — COMMENTED** [review]
Congratulations on your certification @Saaarthak0102

**Comment by Saaarthak0102** [comment]
> Congratulations on your certification @Saaarthak0102 

Thank you sir!

**Comment by IvySingh-1** [comment]
add my certificate please

**Comment by Saaarthak0102** [comment]
> add my name please
> 

Create a PR

**Pull request merged**
