### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by sarthakjalan05**
added my name sarthak jalan

### CODE REVIEW

**Comment by sarthakjalan05** [comment]
please merge this

**Review by Tejashri-Taral — COMMENTED** [review]
There is some technical issue will review it soon

**Comment by sarthakjalan05** [comment]
what problems are there please specify.I could not find any issue. @Tejashri-Taral

**Comment by sarthakjalan05** [comment]
@afnank7865 please remove the requested review from @Tejashri-Taral otherwise it is not merging.I cannot remove the review request.

**Review by afnank7865 — APPROVED** [review]

**Pull request closed without merging**
