### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by hari-dev-003**
Added my certification

### CODE REVIEW

**Review by vivekvardhan2810 — CHANGES_REQUESTED** [review]
Please don't delete other entries.
Raise another PR and just add your details.

**Comment by aslams2020** [comment]
Create a new PR.

**Comment by hari-dev-003** [comment]
Apologize for the error I will look into it and create a new request

**Comment by aslams2020** [comment]
Also, after creating a new PR, don't worry about the merge conflicts(if any) .. we'll resolve it and merge it

**Pull request closed without merging**
