### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by AJ-Athira**
add my certificate

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@AJ-Athira please close this PR.

**Comment by vivekvardhan2810** [comment]
@AJ-Athira you have already a merged PR previously, then why have you created a new PR.

your previous PR was merged 2 weeks ago.

and we can see the postman points of yours on the leaderboard.

please check it.

and please close the PR.

**Comment by vivekvardhan2810** [comment]
@AJ-Athira why have you reopened the PR.

**Comment by AJ-Athira** [comment]
actually the mail i got have the info that i can do the certification again ...can you please make me clear of this (please see the note point)
Screenshot 2024-11-09 165456

**Comment by vivekvardhan2810** [comment]
@AJ-Athira the mail is for other contributors who haven't done their postman certification yet.

**Comment by AJ-Athira** [comment]
oh okay ...Thank you for the clarification and sorry for this trouble and misunderstanding

**Comment by vivekvardhan2810** [comment]
@AJ-Athira okay, no problem.

**Pull request closed without merging**
