### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by sejalkad01**
added my  name

### CODE REVIEW

**Review by MastanSayyad — APPROVED** [review]

**Review by sejalkad01 — COMMENTED** [review]
Kindly please review my work again it's not duplicate and suggest changes because it's 1st time of me doing gssoc i request you to recheck because I am clueless what happened I guess my pull request went twice I am so sorry for that but it was unintentionally

**Comment by sejalkad01** [comment]
Hello @mastan sayyad actually I don't know what happened why you labelled
it duplicate is there any issue or anything to worry about because I don't
know what to do and I accidentally deleted the patch 2 also please guide me

**Comment by MastanSayyad** [comment]
@sejalkad01 Your PR waw already merged and the changes you were going to make were already done. that's why label it was duplicate and closed the PR, nothing to worry about.

**Comment by sejalkad01** [comment]
But i accidentally deleted the patch is it fine?

**Comment by MastanSayyad** [comment]
Yeah its totally fine @sejalkad01

**Comment by sejalkad01** [comment]
Hey @MastanSayyad I am facing and issue downloading my gssoc certificate as it says my email is wrong but it's the same email I had used while registering!I hope you will guide me through this .

**Comment by MastanSayyad** [comment]
Hi @sejalkad01 It's due to the GSSoC was ended on 10th Aug and your PR was merged after the server closed. Therefore you're not eligible for the gssoc certifications

**Pull request closed without merging**
