### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by kjl98**
Added my name

### CODE REVIEW

**Comment by kjl98** [comment]
Hello GSSOC team,
Why this conflict occur?

Screenshot 2024-10-23 153201

**Comment by kjl98** [comment]
Is anybody here?

**Comment by kjl98** [comment]
What should I do to resolve this conflict?

**Comment by parteekxo** [comment]
> What should I do to resolve this conflict?

They will fix it dont worry

**Comment by kjl98** [comment]
okay

**Comment by kjl98** [comment]
How much time will this take?

**Comment by vansh-codes** [comment]
Congratulations for the certificate :octocat:

**Comment by kjl98** [comment]
Thank you so much for this opportunity.

**Pull request merged**
