### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by bharat-c27**
Hello @sanjay-kv and @Princegupta101 , I have successfully completed the **Postman API Fundamentals Student Expert certification**.

Thank you for providing this certification to learn API from Scratch. I really enjoyed and I will continue to search more about API.

### CODE REVIEW

**Comment by bharat-c27** [comment]
Hey @SakshamShandilya , I have resolved the conflicts.
Please can you merge.

Thank you !!

**Review by SakshamShandilya — CHANGES_REQUESTED** [review]
Screenshot 2024-07-28 at 9 19 04 AM


Hey @bharat-c27 Please don't edit/modify others details

**Review by SakshamShandilya — APPROVED** [review]
Awesome you will be able to see your 500 points on the next leaderboard server run, let us know how much time you took to complete it.

**Comment by bharat-c27** [comment]
It took me around 1.5 hour, as I did on my own

**Pull request merged**
