### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by KhajaShaikJalal**
Added my name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@KhajaShaikJalal please close this PR, as your new PR is looking good.

**Comment by KhajaShaikJalal** [comment]
I am completely beginner bro.
Please let me know how to close that PR?

**Comment by vivekvardhan2810** [comment]
@KhajaShaikJalal at the down of your PR, you can see like this

Screenshot_2024-11-05-10-37-32-11_40deb401b9ffe8e1df2f1cc5ba480b12

Just click close pull request button, then it will be closed

**Comment by KhajaShaikJalal** [comment]
Okay @vivekvardhan2810

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Pull request merged**
