### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by AkankshaSinghK**
Added my certification.

### CODE REVIEW

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Comment by RadhikaMalpani1702** [comment]
Congratulations on your certification :octocat:

**Comment by AkankshaSinghK** [comment]
@RadhikaMalpani1702
My PR is merged but on leaderboard score is not showing for this PR.

Please let me know about the same.

**Comment by RadhikaMalpani1702** [comment]
@AkankshaSinghK Points and PR will reflect in next server update

**Comment by AkankshaSinghK** [comment]
No worries, thanks for the update!

**Pull request merged**
