### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Jahnavireddy03**
Added my certification

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
your certificate link is incorrect .
Go to your badge and then click on share and copy the link and paste it here

**Comment by Jahnavireddy03** [comment]
Ok

**Comment by Jahnavireddy03** [comment]
Could you please check it now ??

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
its still incorrect so please open a new pr and provide crt link

**Comment by aslams2020** [comment]
Create a new PR

**Pull request closed without merging**
