### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by anshikak03**
added my name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@anshikak03 please close this PR.

as one your Previous PR was merged now by the team.

**Comment by vivekvardhan2810** [comment]
@anshikak03 please close this PR.

**Comment by anshikak03** [comment]
> @anshikak03 please close this PR.
> 
> as one your Previous PR was merged now by the team.

But sir I didn’t get 500 points on leaderboard after doing api postman work

**Comment by vivekvardhan2810** [comment]
@anshikak03, we can see your name on leaderboard.

image

**Comment by anshikak03** [comment]
> @anshikak03, we can see your name on leaderboard.
> 
> image
> 
> please check your score on leaderboard by searching your github username.
> 
> i hope your query was resolved and cleared.

Ok thank you sir

**Pull request closed without merging**
