### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Jahnavireddy03**
Added my name

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
add your details at the end @Jahnavireddy03

**Comment by Jahnavireddy03** [comment]
Iam unable to find my name could you help with that

**Comment by AKSHITHA-CHILUKA** [comment]
add your name at the end then i can merge your pr , I have not merged it yet so you are unable to see it

**Comment by Jahnavireddy03** [comment]
Yeah I added

**Comment by Jahnavireddy03** [comment]
But when I refresh the page iam unable to see it

**Comment by AKSHITHA-CHILUKA** [comment]
image
Please open a new pr and add your details at the end @Jahnavireddy03

**Review by AKSHITHA-CHILUKA — COMMENTED** [review]
need changed

**Pull request closed without merging**
