### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by KartikG2**
Added my name

### CODE REVIEW

**Review by Hemu21 — APPROVED** [review]

**Comment by KartikG2** [comment]
Did my pull request merged successfully?

**Comment by KartikG2** [comment]
Plz tell me bcz , there r no points or even my name

**Comment by Hemu21** [comment]
Your pr is merged it will take time in next rollout your name will appear

**Comment by KartikG2** [comment]
bro wt about goodies, is there another workshop?

**Comment by Hemu21** [comment]
you can check discord announcements for latest updates.

**Comment by KartikG2** [comment]
Bro send me the discord channel or the link

**Pull request merged**
