### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Anushka1431**
Certificate by Anushka Pawar

### CODE REVIEW

**Review by sanjay-kv — APPROVED** [review]
Awesome , we will merge the change soon and this will be reflected on the leaderboard in a day. Meanwhile keep contributing to the gssoc

**Comment by sanjay-kv** [comment]
Anushka can you raise new PR, there is some conflicts on your PR.

**Comment by Anushka1431** [comment]
Okay I will raise a new PR.
Thanks

**Comment by Anushka1431** [comment]
Hi
I've made another pull request.
It shows conflicts in the branch but those conflicts are not caused by me.
Please look into it.
Thankyou!

**Pull request closed without merging**
