### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by anu2023subiksha**
added my name

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
open new pr 
follow the order and change the number accordingly

**Comment by anu2023subiksha** [comment]
> open new pr follow the order and change the number accordingly

done mam

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr

**Comment by anu2023subiksha** [comment]
> open a new pr

that too done mam

**Comment by AKSHITHA-CHILUKA** [comment]
tag me in your new pr 
follow the numbering order and change it

**Comment by anu2023subiksha** [comment]
> tag me in your new pr follow the numbering order and change it

how to tag you and where to tag you

**Comment by AKSHITHA-CHILUKA** [comment]
just use @ and tag

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA please close this PR.

**Pull request closed without merging**
