### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by MinavKaria**

### CODE REVIEW

**Review by iamkanhaiyakumar — COMMENTED** [review]
give the coreect link of badge

this link is not correct
https://badgr.com/backpack/badges/66339d5baf3e8e0970c21159

**Comment by MinavKaria** [comment]
> give the coreect link of badge
> 
> this link is not correct https://badgr.com/backpack/badges/66339d5baf3e8e0970c21159

@MinavKaria What is wrong ?

**Comment by iamkanhaiyakumar** [comment]
> > give the coreect link of badge
> > this link is not correct https://badgr.com/backpack/badges/66339d5baf3e8e0970c21159
> 
> @MinavKaria What is wrong ?

Your link is not correct , go through video and share correct link of badge

**Comment by MinavKaria** [comment]
> > > give the coreect link of badge
> > > this link is not correct https://badgr.com/backpack/badges/66339d5baf3e8e0970c21159
> > 
> > 
> > @MinavKaria What is wrong ?
> 
> Your link is not correct , go through video and share correct link of badge

Ohh Sorry got it

**Pull request closed without merging**
