### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by smog-root**
kindly add labels gssoc-ext and postman @MastanSayyad .
@AKSHITHA-CHILUKA

### CODE REVIEW

**Comment by smog-root** [comment]
@anniepauline @AKSHITHA-CHILUKA 
kindly merge it! There are no issues!!

**Comment by smog-root** [comment]
@AKSHITHA-CHILUKA kindly merge it!

**Comment by AKSHITHA-CHILUKA** [comment]
do a single commit @smog-root 
open a new pr

**Comment by smog-root** [comment]
@AKSHITHA-CHILUKA done! 👍 https://github.com/GSSoC24/Postman-Challenge/pull/2160

**Pull request closed without merging**
