### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by saimohan11**
Added my certificate

### CODE REVIEW

**Comment by saimohan11** [comment]
Why my pr was not merged

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Comment by saimohan11** [comment]
Thank you for merging 🤗

**Comment by saimohan11** [comment]
@vivekvardhan2810 okay thank you

**Pull request merged**
