### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Nayanika1402**
Kindly merge it.

### CODE REVIEW

**Review by SakshamShandilya — CHANGES_REQUESTED** [review]
Screenshot 2024-07-28 at 8 52 32 AM

Hey @Nayanika1402 Please don't delete others entries. After correcting it please tag me to merge your PR

**Comment by Nayanika1402** [comment]
@SakshamShandilya  Done kindly merge it before any conflicts arise.

**Review by SakshamShandilya — CHANGES_REQUESTED** [review]
Screenshot 2024-07-28 at 9 01 05 AM

Please don't add others in your PR

**Comment by Nayanika1402** [comment]
@SakshamShandilya Done

**Review by SakshamShandilya — APPROVED** [review]
Awesome you will be able to see your 500 points on the next leaderboard server run,
let us know how much time you took to complete it.

**Comment by Nayanika1402** [comment]
@SakshamShandilya I completed it in 50 mins approx.

**Pull request merged**
