### PR TITLE
Update add-your-certificate.md #2518

### PR DESCRIPTION
**Pull request by skanarul8002**
I have succesfully added my name and certificate.Kindly review it .
image

### CODE REVIEW

**Comment by skanarul8002** [comment]
@aslams2020, @vansh-codes  , please review it.
Thank you for providing this type of Contributions.

**Comment by vansh-codes** [comment]
Will be reviewed and merged soon...

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
provide correct link of the badge @skanarul8002

**Comment by skanarul8002** [comment]
@AKSHITHA-CHILUKA , please check , i provide correct url.

**Comment by skanarul8002** [comment]
> Will be reviewed and merged soon...

yeah thanks @vansh-codes

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Pull request merged**
