### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Pallabi03**
Added my name

### CODE REVIEW

**Review by Surigi-Tejasree — APPROVED** [review]

**Review by Surigi-Tejasree — APPROVED** [review]

**Review by vivekvardhan2810 — CHANGES_REQUESTED** [review]
@Pallabi03 please don't delete the older entries.

image

please close this PR, and create a new PR, just add your details at the bottom. don't disturb or delete the previous entries.

**Comment by vivekvardhan2810** [comment]
@Surigi-Tejasree please don't involve in these changes.

i hope you understand.

**Comment by Pallabi03** [comment]
@vivekvardhan2810 Sorry for the misunderstanding but I wrote my name after 2191... you were writing while I was writing.
And further more my PR got accepted then how I delete it now.. please rewrite your PR

**Comment by vivekvardhan2810** [comment]
@Pallabi03 you can do one thing.

you can close this PR.

and add your details at the bottom, and then create new PR, this resolves your problem.

**Review by shreyash3087 — APPROVED** [review]

**Comment by shreyash3087** [comment]
@Pallabi03 No need to do anything,the conflicts are resolved,Thanks for the PR and Congrats on your certification! Your scores will be updated soon.

**Pull request merged**
