### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by SimranShaikh20**
Add me name

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
@SimranShaikh20 already merge

image

**Comment by SimranShaikh20** [comment]
@MastanSayyad 
Yeah but my name conflict is there 
Simran Shaikj is there instead of Simran Shaikh . 
So what to do for that?

**Comment by SimranShaikh20** [comment]
@MastanSayyad 
Can you pls tell me what to do for thag

**Comment by MastanSayyad** [comment]
@SimranShaikh20 updated it

**Comment by SimranShaikh20** [comment]
> @SimranShaikh20 updated it

@MastanSayyad  Thank you

**Comment by SimranShaikh20** [comment]
@MastanSayyad  i want ask that after postman course  how we can contribute in it? 
Or this is for only learning propose only!

**Comment by MastanSayyad** [comment]
Yes it is for learning purpose and it completely your choice if you want to explore more or not

**Pull request closed without merging**
