### PR TITLE
Added Postman API Fundamentals Student Expert certificate

### PR DESCRIPTION
**Pull request by nehaw04**
This PR adds my Postman API Fundamentals Student Expert certificate to the repository.

### CODE REVIEW

**Comment by aslams2020** [comment]
@nehaw04 Please add your details. 
image

**Create a new PR please**

**Comment by nehaw04** [comment]
Where should I add my details

**Comment by aslams2020** [comment]
In the `add-your-certificate.md` file..
Scroll down to last and Add your name, LinkedIn id, certificate link and Feedback.
 In the same format others have added.

After that create a PR, and don't worry if any merge conflicts are there, we will merge it after resolving.

**Comment by nehaw04** [comment]
Accidently ,I have posted without creating a pull request.

**Comment by aslams2020** [comment]
You can make a new PR. No worries.

**Pull request closed without merging**
