### PR TITLE
noice

### PR DESCRIPTION
**Pull request by ShashwatAgrawal20**
It should work, but I can't verify it as I don't have access to the real data. I've also added a script that removes duplicate entries based on email addresses. **Note that this script doesn't rename the numbers; you'll need to do that manually. Since I use neovim btw, this isn't an issue for me—I can use macros and the increment feature to handle that.**

### CODE REVIEW

**Comment by ShashwatAgrawal20** [comment]
@sanjay-kv it would be beneficial if you review and merge this PR before any other.

> [!IMPORTANT]  
> Only merge this if you're 100% sure

**Comment by ShashwatAgrawal20** [comment]
don't merge this yet, I'm refactoring the duplication remover script

**Comment by ShashwatAgrawal20** [comment]
done, now it's ready for merge the script now also has some error handling stuff, you can even toggle a commented line in the script which will also show you which line the script is discarding(duplicates):- L31

image

OR with the line commented(default)
image


IF no duplicates are found it will inform you that way
image

**Comment by ShashwatAgrawal20** [comment]
@sanjay-kv @Princegupta101

**Comment by Princegupta101** [comment]
> @sanjay-kv @Princegupta101

Ok if everything is fine than we add it @ShashwatAgrawal20

**Comment by ShashwatAgrawal20** [comment]
> > @sanjay-kv @Princegupta101
> 
> Ok if everything is fine than we add it @ShashwatAgrawal20

sure, just a favor—please hold off on merging any other PRs for now as they are quite problematic.

**Review by Princegupta101 — CHANGES_REQUESTED** [review]
sorry in your list 250 
but in main list 450+
also no need any other 
duplicate_remover.py

**Comment by ShashwatAgrawal20** [comment]
yeye, that makes sense. I didn't consider your changes and assumed you had only removed a few items, so I continued with the previous version. My apologies for the oversight.

**Comment by Wahid7852** [comment]
> sorry in your list 250 but in main list 450+ also no need any other duplicate_remover.py

exactly, he used the duplication script and nuked those duplicates, checked the changes?

**Pull request closed without merging**
