### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Nihalcodes**
added my name Shaik Nihal

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
@aslams2020 please merged it

**Comment by Nihalcodes** [comment]
[image: image.png]
What should i do now? Please guide me

**Comment by vivekvardhan2810** [comment]
@Nihalcodes No need to do anything, the team will resolve the merge conflicts and they will merge your PR, please wait for the team.

**Comment by aslams2020** [comment]
Hi @Nihalcodes 
Please create a new, as this PR has some technical issues ig

**Pull request closed without merging**
