### PR TITLE
Updated certificate.md

### PR DESCRIPTION
**Pull request by Anshika14528**
Added my postman certification completion details

### CODE REVIEW

**Comment by Anshika14528** [comment]
@Princegupta101 sir and @sanjay-kv sir please review and merge it.

**Review by Princegupta101 — CHANGES_REQUESTED** [review]
hey, we have issue in merging your PR, could you raise the PR again. Sorry for the trouble.
@Anshika14528

**Comment by Anshika14528** [comment]
@Princegupta101 sir i have added again the PR #833 please review it and merge it please.

**Comment by Princegupta101** [comment]
Ok

**Pull request closed without merging**
