### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by priyashuu**

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
add it at the last @priyashuu

**Review by AKSHITHA-CHILUKA — COMMENTED** [review]
ok

**Comment by priyashuu** [comment]
BUT mam its already merged na

**Comment by AKSHITHA-CHILUKA** [comment]
yup its fine

**Comment by priyashuu** [comment]
thank you mam @AKSHITHA-CHILUKA

**Pull request merged**
