### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Pranshu-jais**

### CODE REVIEW

**Comment by Pranshu-jais** [comment]
@SakshamShandilya how can i resolve my conflict https://github.com/GSSoC24/Postman-Challenge/pull/190.

**Comment by Pranshu-jais** [comment]
@SakshamShandilya    Sir kindly help me to resolve this conflicts  ,  i tried  to resolve it many times but failed.

**Comment by SakshamShandilya** [comment]
I will check, don't worry I'll resolve the conflicts

**Comment by Pranshu-jais** [comment]
> I will check, don't worry I'll resolve the conflicts @Pranshu-jais

thanks

**Pull request merged**
