### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Yashu04**
added name

### CODE REVIEW

**Comment by Yashu04** [comment]
https://www.linkedin.com/posts/yashashree-panhale-008090257_postman-api-fundamentals-student-expert-activity-7255661087511957504-0Tz_?utm_source=share&utm_medium=member_desktop

**Comment by aslams2020** [comment]
Your Previous PR has already been merged. your scores will get reflected in next server update! ⚡

**Comment by Yashu04** [comment]
Where will be the points reflected ?

**Comment by aslams2020** [comment]
In GSSoC official website > Leaderboard

**Pull request closed without merging**
