### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Bhawnarajput1502**
I have  successfully completed the Postman API Fundamentals course for students, which has provided me with a thorough understanding of the core principles of API
development, testing, GET , POST , PATCH and DELETE.

### CODE REVIEW

**Comment by Bhawnarajput1502** [comment]
Please merged my PR @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Hi, @Bhawnarajput1502 firstly i am not a part of the GSSOC team,

i am just an observer, i can't merge any PR'S of postman, the team will look into your PR, they will merge this.

i hope you understand.

**Comment by Bhawnarajput1502** [comment]
"Please review this PR" .Is it ready to be merge? @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@Bhawnarajput1502 i have reviewed it, it will be merged soon by the team.

please wait.

**Comment by Bhawnarajput1502** [comment]
"I have resolved all conflicts " @vivekvardhan2810

**Comment by Bhawnarajput1502** [comment]
Please merged my PR @ AKSHITA-CHILUKA

**Review by shreyash3087 — APPROVED** [review]

**Comment by shreyash3087** [comment]
@Bhawnarajput1502 Thanks for the PR and Congrats on your certification! Your scores will be updated soon.

**Pull request merged**
