### PR TITLE
Updated for swatified

### PR DESCRIPTION
**Pull request by swatified**
Here's my credentials for the postman challenge executed during gssoc-extended 2024. Kindly check them out.

### CODE REVIEW

**Review by vansh-codes — APPROVED** [review]

**Comment by vansh-codes** [comment]
Congratulations for the certificate :octocat:

**Comment by swatified** [comment]
@vansh-codes thank youu, that was fast!

**Comment by swatified** [comment]
@vansh-codes Why was my score not reflected in the leaderboard that got updated at 12 last night? 😭

**Comment by vansh-codes** [comment]
It is updated

**Pull request merged**
