### PR TITLE
Update add-your-certificate.md for Supriya Gorai

### PR DESCRIPTION
**Pull request by SupriyaGo**

### CODE REVIEW

**Comment by SupriyaGo** [comment]
Please check @AKSHITHA-CHILUKA

**Review by AKSHITHA-CHILUKA — APPROVED** [review]
good work

**Comment by SupriyaGo** [comment]
When it will reflect in the Leaderboard ? @AKSHITHA-CHILUKA

**Comment by AKSHITHA-CHILUKA** [comment]
in the next server run it will be reflected on the leaderboard @SupriyaGo

**Comment by SupriyaGo** [comment]
Thank you @AKSHITHA-CHILUKA

**Pull request merged**
