### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by VemuriHaritha**
added name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@VemuriHaritha  you have already created the pull request previously, why are you creating the PR again.

if you are worrying about the branch and merge conflicts, the team will resolve it and merge your PR.

please close this PR.

**Comment by vivekvardhan2810** [comment]
@VemuriHaritha if you are worrying about the branch and merge conflicts, don't worry the team will resolve it and merge your PR.

please close this PR.

**Comment by vivekvardhan2810** [comment]
@RadhikaMalpani1702 please check and merge this PR.

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Pull request merged**
