### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by SanikaBhalerao1345**
Name: Sanika Bhalerao
Added my name

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — APPROVED** [review]
great!

**Comment by SanikaBhalerao1345** [comment]
Thanks @AKSHITHA-CHILUKA when will my points be added in leaderboard

**Comment by AKSHITHA-CHILUKA** [comment]
You can check now @SanikaBhalerao1345

**Comment by SanikaBhalerao1345** [comment]
Thanks!! @AKSHITHA-CHILUKA

**Pull request merged**
