### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by NehaJOShi259**
added my name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@NehaJOShi259 you have already created the PR previously, why are you creating the PR again.

if you are worrying about the branch and merge conflicts, don't worry the team will resolve it and merge your PR.

please close this PR.

**Comment by vivekvardhan2810** [comment]
@NehaJOShi259 please don't repeat this.

**Comment by vivekvardhan2810** [comment]
@NehaJOShi259 please close this PR.

 you have already created the PR previously, why are you creating the PR again and again.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 I had a talk with the contributor regarding the problem with score on the leaderboard. I have asked the contributor to close this duplicate PR as you have asked.
The other PR opened by this PR is open. Please review the PR and merge it at your convenience:
- https://github.com/GSSoC24/Postman-Challenge/pull/3901

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc yes, the team will review this.

firstly i am not a part of the GSSOC team,

i am just an observer and reviewer, i can't merge any PR'S of postman, the team will look into your PR, they will do it.

i hope you understand.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 Ok. Sorry for the inconvenience. 
Thanks for the confirmation.

**Pull request closed without merging**
