### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by TanushriS**
Added my name

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr do not delete others details 
image
just add your details at the end

**Comment by TanushriS** [comment]
> open a new pr do not delete others details image just add your details at the end

**Comment by AKSHITHA-CHILUKA** [comment]
yeah create a new one and just add your details at the end and follow the numbering

**Comment by TanushriS** [comment]
> yeah create a new one and just add your details at the end and follow the numbering

pull request closed. Plz help

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr @TanushriS i will merge it

**Comment by AKSHITHA-CHILUKA** [comment]
or else wait open a new pr in https://github.com/sanjay-kv/Open-source-Practice this repo 
regarding the postman pr

**Comment by AKSHITHA-CHILUKA** [comment]
https://github.com/sanjay-kv/Open-source-Practice/pull/1512 check her pr and follow the same

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA please close this PR, as you have merged one of her PR.

**Comment by AKSHITHA-CHILUKA** [comment]
merged your pr

**Pull request closed without merging**
