### PR TITLE
Update add-your-certificate.PrabhjotBajwa

### PR DESCRIPTION
**Pull request by PrabhjotBajwa**

### CODE REVIEW

**Comment by PrabhjotBajwa** [comment]
@Princegupta101 plz merge my pr

**Comment by PrabhjotBajwa** [comment]
now see @Princegupta101

**Review by Princegupta101 — APPROVED** [review]
Awesome you will be able to see your 500 points on next leaderboard server run,
let us know how much time you took to complete it.

**Comment by Princegupta101** [comment]
> now see @Princegupta101

Not delete anyone 
You deleted the akshitha @PrabhjotBajwa

**Comment by PrabhjotBajwa** [comment]
@Princegupta101 sorry my bad 😞

**Comment by PrabhjotBajwa** [comment]
@Princegupta101 didn't receive 500 points on leaderboard. Initially it was there but now it is showing only 280 earlier it was 780

**Pull request merged**
