### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Overhere7**
Add the certificate with details in the repo

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
change the number @Overhere7 check the list and change the number accordingly

**Comment by AKSHITHA-CHILUKA** [comment]
2739 is done so change it to 2740

**Comment by Overhere7** [comment]
ok sure

**Comment by Overhere7** [comment]
Added a new PR please accept it

**Pull request closed without merging**
