### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Unknownmaster0**
Added my name, with the link of postman student expert badge and LinkedIn profile.

### CODE REVIEW

**Review by SakshamShandilya — APPROVED** [review]
Okay

**Review by sanjay-kv — APPROVED** [review]
Awesome. you will be getting 500 points after merging let us know how long you took to complete it.

**Comment by sanjay-kv** [comment]
@SakshamShandilya Make sure you assign the person as well.

**Comment by SakshamShandilya** [comment]
> @SakshamShandilya Make sure you assign the person as well. 

Okay

**Comment by DharshiBalasubramaniyam** [comment]
@sanjay-kv @SakshamShandilya @Unknownmaster0 
My details are over written by this pr 

image

**Comment by SakshamShandilya** [comment]
> @sanjay-kv @SakshamShandilya @Unknownmaster0 
> 
> My details are over written by this pr. is that okay?
> 
> 
> 
> image
> 
> 

Can you raise another pr @DharshiBalasubramaniyam ?

**Comment by DharshiBalasubramaniyam** [comment]
> > @sanjay-kv @SakshamShandilya @Unknownmaster0
> > My details are over written by this pr. is that okay?
> > image
> 
> Can you raise another pr @DharshiBalasubramaniyam ?

alright

**Comment by DharshiBalasubramaniyam** [comment]
Hello @SakshamShandilya @sanjay-kv , As you mentions i have created another pr(#66). And you have merged it. but you have added postman label in both prs. because of that both 2 prs are showing in the leaderboard and lead to 1000points. 

image

I think this is not a valid behavior. You have to remove the label from this pr. Kindly take any action regarding this.

**Comment by SakshamShandilya** [comment]
> Hello @SakshamShandilya @sanjay-kv , As you mentioned i have created another pr(#55 and #66). And you have merged it. but you have added postman label in both prs. because of that both 2 prs are showing in the leaderboard and lead to 1000points.
> 
> image
> 
> I think this is not a valid behavior. You have to remove the label from this pr. Kindly take any action regarding this.
> 
> And kindly make sure, You did not do this mistake to other as well.

Thank you for letting us know!

**Pull request merged**
