### PR TITLE
Added Postman Challenge

### PR DESCRIPTION
**Pull request by SadafKausar2025**
https://api.badgr.io/public/assertions/WenGeNc6Sg2QB2wPg3N_6Q?identity__email=sadafkausar2003%40gmail.com

Screenshot 2024-07-25 110157

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @Princegupta101 
please review this PR and merge it

**Comment by SadafKausar2025** [comment]
hello @Princegupta101 
because you are merge up , I got soo many conflict

**Comment by Princegupta101** [comment]
> hello @Princegupta101 because you were merging up , I got soo many conflict

I will resolve wait

**Comment by SadafKausar2025** [comment]
> > hello @Princegupta101 because you were merging up , I got soo many conflict
> 
> I will resolve wait

I resolved the conflict 5 times

**Comment by SadafKausar2025** [comment]
hello @Princegupta101 
now you can merge it

**Comment by SadafKausar2025** [comment]
hello @sanjay-kv and @Princegupta101 
please merge it

**Review by sanjay-kv — CHANGES_REQUESTED** [review]
could you request again, you changing a lot of other people format

**Pull request closed without merging**
