### PR TITLE
Create certificate postman challenge

### PR DESCRIPTION
**Pull request by ankita685**
https://api.badgr.io/public/assertions/1HeccHObQ4OqJO2RNpPxxg?identity__email=ankitawork26%40gmail.com

### CODE REVIEW

**Comment by ankita685** [comment]
@Princegupta101 
pls merge my pr

**Comment by ankita685** [comment]
Postman - Postman API Fundamentals Student Expert - 2024-07-27

**Comment by ankita685** [comment]
Certificate

**Comment by sanjay-kv** [comment]
could you raise the PR in correct format

**Pull request closed without merging**
