### PR TITLE
feat(addName): add name with Postaman API certification

### PR DESCRIPTION
**Pull request by kaiyumdev**
Add Name with Postman certification

### CODE REVIEW

**Comment by kaiyumdev** [comment]
Thanks for the information @vivekvardhan2810

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Comment by kaiyumdev** [comment]
Thank you @RadhikaMalpani1702! My PR has been merged—will any score from this merge be added to my profile and reflected on the leaderboard?

**Comment by vivekvardhan2810** [comment]
@kaiyumdev yes, you can check your after sometime on leaderboard.

As the leaderboard updates twice a day.

**Comment by kaiyumdev** [comment]
@vivekvardhan2810 Thank you for the information! I’ll check the leaderboard later.

**Pull request merged**
