### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by ujjwalshriv3**
Added my name

### CODE REVIEW

**Review by ujjwalshriv3 — COMMENTED** [review]
plz  merge my PR @sanjay-kv

**Review by MastanSayyad — APPROVED** [review]

**Comment by MastanSayyad** [comment]
Congratulations on your certifications! Your PR is merged, though it was received a bit late there won't be any Postman points added to the leaderboard as we've stopped the server. However, you can still fill out the form for swags. We select 25 winners in each batch @ujjwalshriv3

**Comment by ujjwalshriv3** [comment]
Plz give me a certificate when I entered my correct email it's not verified my email how can I download my certificate plz provide me a certificate 🙏

**Comment by MastanSayyad** [comment]
@ujjwalshriv3 GSSoC ended on August 10th, 2024, so you are not eligible for the certificate. The Postman certification is still live until August 30th/31st.

**Comment by ujjwalshriv3** [comment]
Ya I know it's my fault I'm not aware this such  type of that massage but still I try harder more for certificate what can I do now plz if u can try then hope you provide me certificate 🥲@MastanSayyad

**Pull request merged**
