### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by RishabhRawatt**
added certificate and info on certificate.md

### CODE REVIEW

**Review by aslams2020 — APPROVED** [review]
Congratulations for your certification! your scores will get reflected in next server update! ⚡

**Comment by RishabhRawatt** [comment]
Will it merge?

**Comment by aslams2020** [comment]
@AKSHITHA-CHILUKA Can u Please merge it. Currently you are resolving PRs so accordingly.

**Comment by aslams2020** [comment]
@RishabhRawatt Please dont resolve the conflicts. It'll create confusion. let it be, we will merge it

**Comment by RishabhRawatt** [comment]
Sure thanks 🎆

**Review by aslams2020 — COMMENTED** [review]
Congratulations for your certification! your scores will get reflected in next server update! ⚡

**Pull request merged**
