### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by manikumarreddyu**
added manikumarreddyu's certificate after completing the course

### CODE REVIEW

**Comment by manikumarreddyu** [comment]
@Princegupta101 Kindly merge this please

**Comment by manikumarreddyu** [comment]
@sanjay-kv Kindly merge this please

**Comment by manikumarreddyu** [comment]
@SakshamShandilya can you please check it once

**Comment by sanjay-kv** [comment]
you need to raise new PR there is conflicts

**Pull request closed without merging**
