### PR TITLE
Updated my name in add-your-certificate.md

### PR DESCRIPTION
**Pull request by SurajjBhardwaj**

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]
Thank you for creating the PR, The GSSOC Team will look into your PR very soon, and they will update and merge it.

Even if the merge conflicts comes, Don't worry the team will resolve the merge conflicts and they will merge this.

so please wait.

**Comment by SurajjBhardwaj** [comment]
btw can you confirm that for the goodies, do I need to make the LinkedIn post ? because I have already added it in certificate category.

**Comment by vivekvardhan2810** [comment]
@SurajjBhardwaj But for the linkedin post which you have created for postman, that linkedin post link is for the postman swags/ Goodies. challenge.

Also you can participate in Postman goodies giveaway , read about the giveaway here -> https://www.linkedin.com/posts/girlscriptsoc_postman-gssoc-gssocext-activity-7256915836408365057-iRKv?utm_source=share&utm_medium=member_desktop

For more information and step by step guide check out this page: https://gssoc.girlscript.tech/postmanChallenge.

Note: it's not mandatory that everyone win and gets goodies because it's a random winners so who completed the postman challenge and share it on social media and tag GSSOC.

**Comment by SurajjBhardwaj** [comment]
i mean to say that the twitter post will also count for goodies giveaway right ?

**Comment by SurajjBhardwaj** [comment]
no i have posted it on twitter, 

https://x.com/Surajjbhardwajj/status/1853758117840093282

do i need to update it in my pr ??

**Comment by vivekvardhan2810** [comment]
@SurajjBhardwaj No need to update this twitter link on PR,

📲 𝗦𝗵𝗮𝗿𝗲 𝗼𝗻 𝗧𝘄𝗶𝘁𝘁𝗲𝗿 𝗳𝗼𝗿 𝗘𝗹𝗶𝗴𝗶𝗯𝗶𝗹𝗶𝘁𝘆!
This is a Twitter Giveaway, so share your achievement with the community.

there will be a google form to share this link.

**Pull request merged**
