### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by xdvraj**
@AKSHITHA-CHILUKA merge this pr

### CODE REVIEW

**Comment by DevBhalgamiya** [comment]
Change your serial number 2465 to 2467 then i can approve your pull request

**Comment by xdvraj** [comment]
Changed

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
provide your LinkedIn link @xdvraj

**Comment by xdvraj** [comment]
I have to make a new pull request with the same number?

**Comment by AKSHITHA-CHILUKA** [comment]
use the last number coming in the series

**Comment by xdvraj** [comment]
Done ✅

**Pull request closed without merging**
