### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by spandanapatta**
Added my name

### CODE REVIEW

**Review by Asymtode712 — APPROVED** [review]

**Comment by MastanSayyad** [comment]
Hey @Asymtode712 you should have reviewed the file, this contributor has deleted the data of three other contributors still no worries! i will edit the original one add the data but make sure you review the code you see more than 1 minus lines of code

**Comment by Asymtode712** [comment]
@MastanSayyad Apologies, actually I am editing all the PRs with merge conflicts and this didn't had one so I merged it directly, would check each PR thoroughly now onwards, thanks for pointing this out

**Comment by MastanSayyad** [comment]
@Asymtode712 No, it's fine! don't apologize

**Comment by Asymtode712** [comment]
@MastanSayyad I have made the changes and removed a duplicate contributor details

**Pull request merged**
