### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by yashp386**
add certificate

### CODE REVIEW

**Comment by yashp386** [comment]
added certificate

**Comment by vivekvardhan2810** [comment]
@yashp386 you have already created the pull request previously, why are you creating the PR again.

if you are worrying about the branch and merge conflicts, the team will resolve it and merge your PR.

**Comment by yashp386** [comment]
sorry i thought my pr didn't created due to internet problem

**Comment by yashp386** [comment]
sorry i had internet issue so i thought my pr didn't got created btw how to
resolve conflicts now??

**Comment by vivekvardhan2810** [comment]
@yashp386 no need of resolving the conflicts.

the team will resolve the conflicts and merge your PR.

**Comment by yashp386** [comment]
Ok, thank you .. hope it will get solved soon

**Comment by yashp386** [comment]
@vivekvardhan2810 please merge my pr last 3 days left sir..

**Comment by vivekvardhan2810** [comment]
Hi, @yashp386 i am not a part of the GSSOC team, 

i am just an observer, i can't merge this, the team will look into your PR, they will merge this.

i hope you understand.

**Pull request closed without merging**
