### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Anjaliavv51**

### CODE REVIEW

**Comment by Anjaliavv51** [comment]
@Princegupta101 please merge the PR

**Comment by Anjaliavv51** [comment]
@sanjay-kv  @Princegupta101 please merge the PR , it has no conflicts

**Comment by Anjaliavv51** [comment]
@sanjay-kv  @Princegupta101 please merge the PR , it has no conflicts

**Review by Princegupta101 — APPROVED** [review]
Awesome you will be able to see your 500 points on next leaderboard server run,
let us know how much time you took to complete it.

**Pull request merged**
