### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Akanksha12-i**
Added my name and certificate

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
change the numbering according to the order
and tag me I will merged it 
open a new pr

**Comment by Akanksha12-i** [comment]
ok, I'm doing it.

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr

**Comment by Akanksha12-i** [comment]
@AKSHITHA-CHILUKA New pr at #4342

**Pull request closed without merging**
