### PR TITLE
Added the details

### PR DESCRIPTION
**Pull request by SOMNATH0904**
Added the details

### CODE REVIEW

**Comment by SOMNATH0904** [comment]
@SakshamShandilya Kindly Merge this PR. Currently, this is not having any conflicts. Thank You!

**Comment by SakshamShandilya** [comment]
> @SakshamShandilya Kindly Merge this PR. Currently, this is not having any conflicts. Thank You!

Sure

**Review by SakshamShandilya — CHANGES_REQUESTED** [review]
Hey @SOMNATH0904 Can you please add the valid certification link , as the one you added is not accessible

**Review by SakshamShandilya — CHANGES_REQUESTED** [review]
Screenshot 2024-07-28 at 8 42 58 AM

**Comment by SOMNATH0904** [comment]
@SakshamShandilya Wait

**Comment by SOMNATH0904** [comment]
@SakshamShandilya https://api.badgr.io/public/assertions/jkMG1MyqRZ2X1g9Y_EqJxA?identity__email=somnath.arcade3.2024%40gmail.com

**Comment by SakshamShandilya** [comment]
> @SakshamShandilya https://api.badgr.io/public/assertions/jkMG1MyqRZ2X1g9Y_EqJxA?identity__email=somnath.arcade3.2024%40gmail.com

Okay works well

**Comment by SOMNATH0904** [comment]
> > @SakshamShandilya https://api.badgr.io/public/assertions/jkMG1MyqRZ2X1g9Y_EqJxA?identity__email=somnath.arcade3.2024%40gmail.com
> 
> Okay works well , can you please change it in the PR also ? @SOMNATH0904

Okay doing

**Comment by SOMNATH0904** [comment]
> > @SakshamShandilya https://api.badgr.io/public/assertions/jkMG1MyqRZ2X1g9Y_EqJxA?identity__email=somnath.arcade3.2024%40gmail.com
> 
> Okay works well , can you please change it in the PR also ? @SOMNATH0904

@SakshamShandilya Please Check now ...

**Review by SakshamShandilya — APPROVED** [review]
Awesome you will be able to see your 500 points on the next leaderboard server run,
let us know how much time you took to complete it.

**Pull request merged**
