### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by anshikak03**
added my name and linkedin profile

### CODE REVIEW

**Comment by anshikak03** [comment]
i have try to resolve this

**Review by dikshakshirsagar — APPROVED** [review]

**Review by dikshakshirsagar — APPROVED** [review]

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Comment by anshikak03** [comment]
@RadhikaMalpani1702 
Mam I didn’t get 500 points on leaderboard

**Comment by vivekvardhan2810** [comment]
@anshikak03 

image

**Pull request merged**
