### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by SathvigaaBharathi**
added name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@SathvigaaBharathi Don't create Multiple PR'S at a single time.

already you have previously create the PR.

please wait.

The GSSOC Team will look into your PR and they will update it.

**Comment by SathvigaaBharathi** [comment]
Thanks for letting know and sorry for any inconvenience occured.

**Comment by SathvigaaBharathi** [comment]
May I know when will the points be reflected in leaderboard?

**Comment by vivekvardhan2810** [comment]
@SathvigaaBharathi The GSSOC Team will look into your PR and they will merge it, then after sometime you can see your 500 points score on leaderboard And your name.

As the leaderboard updates twice a day.

**Comment by vivekvardhan2810** [comment]
@aslams2020 you can close this PR, as you have merged her Previous PR.

**Comment by vivekvardhan2810** [comment]
@aslams2020 you can close this PR, as you have merged one of her Previous PR.

**Comment by aslams2020** [comment]
Merged #3304

**Comment by aslams2020** [comment]
Thanks Vivek!

**Pull request closed without merging**
