### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by meetalik8**
Added Meetali's certificate after completing the course

### CODE REVIEW

**Review by SakshamShandilya — APPROVED** [review]
Awesome you will be able to see your 500 points on the next leaderboard server run, let us know how much time you took to complete it.

**Comment by Pranshu-jais** [comment]
@SakshamShandilya  how can i resolve my conflict  https://github.com/GSSoC24/Postman-Challenge/pull/190

**Comment by SakshamShandilya** [comment]
> @SakshamShandilya how can i resolve my conflict #190

I will do that for you please tag me in your PR

**Comment by Pranshu-jais** [comment]
> > @SakshamShandilya how can i resolve my conflict #190
> 
> I will do that for you please tag me in your PR
i have tagged you in my PR https://github.com/GSSoC24/Postman-Challenge/pull/190

**Pull request merged**
