### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by DivyaCodingWorld**
added my Name

### CODE REVIEW

**Review by shreyash3087 — APPROVED** [review]

**Comment by shreyash3087** [comment]
@DivyaCodingWorld Thanks for the PR and Congrats on your certification! Your scores will be updated soon.

**Comment by DivyaCodingWorld** [comment]
@shreyash3087 Please update my scores /points on leaderboard..

**Comment by shreyash3087** [comment]
@DivyaCodingWorld  Its already updated
Screenshot (930)

**Comment by DivyaCodingWorld** [comment]
@shreyash3087 Thanks..

**Comment by DivyaCodingWorld** [comment]
@shreyash3087 I tried downloading my certificate via the link shared in the email registered for GSSOC 2024 extended. I even have my badge downloaded and there, verification was successful. However, at certificate page, the verification is showing failed.
Please look into it :)
Screenshot (167)

**Comment by DivyaCodingWorld** [comment]
@shreyash3087    Email-id : divyanipatel2022@gmail.com
Name: Divyani Patel
Git-hub Id: https://github.com/DivyaCodingWorld

**Comment by shreyash3087** [comment]
@DivyaCodingWorld Thanks,You'll be able to download your certification within the next 12 hrs

**Comment by DivyaCodingWorld** [comment]
@shreyash3087 Ok Sir, I will check soon..

**Pull request merged**
