### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Aasthaa10**
Added my name ,certificate and my linkedin

### CODE REVIEW

**Comment by Aasthaa10** [comment]
@MastanSayyad sir please help me resolve this conflict

**Review by vansh-codes — APPROVED** [review]
Congratulations for the certificate :octocat:

**Comment by Aasthaa10** [comment]
Thankyouu🥹

**Comment by Aasthaa10** [comment]
can you tell me that tommorrow my points 500 will be reflected on the leaderboard

**Comment by MastanSayyad** [comment]
Yes, in morning around 6 or 6;30

**Pull request merged**
