### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Balasubramanyam-Chilukala**

### CODE REVIEW

**Review by vivekvardhan2810 — APPROVED** [review]
Thank you for creating the PR, The GSSOC Team will look into your PR very soon, and they will update and merge it.

Even if the merge conflicts comes, 

Don't worry the team will resolve the merge conflicts and they will merge your PR.

so please wait.

**Comment by Balasubramanyam-Chilukala** [comment]
Yeah, Thank you.

**Comment by vivekvardhan2810** [comment]
@RadhikaMalpani1702 please merge this PR.

**Comment by vivekvardhan2810** [comment]
@RadhikaMalpani1702 please check and merge this PR.

**Review by RadhikaMalpani1702 — APPROVED** [review]

**Review by RadhikaMalpani1702 — COMMENTED** [review]
Congratulations for your certification :octocat:

**Pull request merged**
