### PR TITLE
Readded name - ( I dont know somebody removed my name from the list..…

### PR DESCRIPTION
**Pull request by arunimaChintu**
….. Please check PR's before merging

### CODE REVIEW

**Comment by arunimaChintu** [comment]
#470 this was my pr that you merged, but now my name is completely removed from the add-certificate list.... Please check and report that user,....

**Review by Asymtode712 — APPROVED** [review]

**Comment by arunimaChintu** [comment]
@Asymtode712 you removed labels in both of my Prs

**Comment by arunimaChintu** [comment]
@Asymtode712 Please add it asap!

**Comment by arunimaChintu** [comment]
There is no labels in any of my 2 merged PRs, please have a look asap

**Comment by Asymtode712** [comment]
Hey @arunimaChintu , so sorry for delay caused in adding the labels

**Pull request merged**
