### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by mohitrajjha111**

### CODE REVIEW

**Comment by sanjay-kv** [comment]
Awesome Work,
if you think I helped you somehow on opensource learning and postman  kindly nominate me in the below link:
my unicorn id is : sanjay-kv

you can select the reason as : how I helped you with opensource or being a PM how it helped you in doing your first commit.
This would be a good gesture and motivation for me to more towards community.
https://stars.github.com/nominate/

**Comment by mohitrajjha111** [comment]
@sanjay-kv I elected you on it weeks ago when the first time we got the option to nominate you as github star.
You are the one who made me realise its not that hard. Even I can do it if I put my hardwork in it.
Thank you for being there for us and introducing us to the awesome opensource world out there.

**Comment by mohitrajjha111** [comment]
@sanjay-kv maybe you forgot to add the postman label. please see to it. Thank you.

**Comment by mohitrajjha111** [comment]
@sanjay-kv @Princegupta101 Postman label is missing. Please see to it. Thank You

**Comment by mohitrajjha111** [comment]
@sanjay-kv @Princegupta101

**Comment by mohitrajjha111** [comment]
@sanjay-kv @Princegupta101 Please See to it.

**Comment by mohitrajjha111** [comment]
@Hemu21 Please add postman label. Thank You

**Pull request merged**
