### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Smridul3004**
added my name

### CODE REVIEW

**Review by MastanSayyad — COMMENTED** [review]
Congratulations on your certifications!

**Comment by Smridul3004** [comment]
Is there any issue with my request?
I have added my certifications already.
If any Please notify me as soon.
Thankyou for the support !!

**Comment by MastanSayyad** [comment]
No @Smridul3004 I’ve approved your PR, though it was received a bit late please note that there won't be any Postman points added to the leaderboard as we've stopped the server. However, you can still fill out the form for swags. We select 25 winners in each batch.

**Comment by Smridul3004** [comment]
Oh My name is mentioned in the list then for swags?

**Pull request merged**
