### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by praneethaBrindavanam**
| Brindavanam Praneetha | [Brindavanam Praneetha](www.linkedin.com/in/brindavanampraneetha)  | [Certificate link](https://api.badgr.io/public/assertions/IWK7_BKWSeaHCxBeGbwSAA?identity__email=praneethabrindavanam04%40gmail.com) | Great Platform indeed. |

### CODE REVIEW

**Review by aslams2020 — APPROVED** [review]

**Review by aslams2020 — COMMENTED** [review]
Congratulations for your certification! your scores will get reflected in next server update! ⚡

**Review by praneethaBrindavanam — COMMENTED** [review]
thank you

**Comment by praneethaBrindavanam** [comment]
@aslams2020 can i check for leaderboard??

**Comment by aslams2020** [comment]
@praneethaBrindavanam You'll be able to see your points, in morning leaderboard update

NOTE : The leaderboard updates twice a day, first in the morning and second in the evening.

**Pull request merged**
