### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by vidya-chauhan04**
add my name

### CODE REVIEW

**Comment by MastanSayyad** [comment]
The gssoc program has ended  postman challenge points will not reflect in the gssoc leaderboard (as it is already finalized)

**Comment by Sakshiroy7870** [comment]
I have completed the challenge nd got the batch before gssoc deadline kindly reflect my point in leaderboard.

**Comment by MastanSayyad** [comment]
> I have completed the challenge nd got the batch before gssoc deadline kindly reflect my point in leaderboard.

You were supposed to raise a PR before 10th Aug 7:00 pm, PR counting deadline was on that day

**Comment by Sakshiroy7870** [comment]
I didn't watched the videos to raise the PR that's why I raised it late but
completed the challenge before deadline u can check the certificate.

**Review by sanjay-kv — APPROVED** [review]
Hi,
I have approved your commit, as we received this bit late.
There wont be any postman points on leaderboard, as we stopped the server.
You can fill the form for swags again every batch we select 25 winners on the same.

Nominate Me on GitHub : If you’ve found my guidance helpful, I’d appreciate if you [could nominate me for the GitHub program](https://stars.github.com/nominate/). You can use my GitHub ID: sanjay-kv and mention how I’ve helped you get started with open source.

My GitHub ID: [sanjay-kv](https://github.com/sanjay-kv) (lets connect each other by following , will be following you back as well)

**Pull request merged**
