### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by 121hemank**
added my name

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
image
open a new pr , do not change other details just add your details @121hemank

**Comment by 121hemank** [comment]
I have not changed other details

**Comment by AKSHITHA-CHILUKA** [comment]
I can see it that you have removed the details and added yours

**Comment by 121hemank** [comment]
of whose now i am again adding my detail at number 1624 and i have not
removed anyone details

**Pull request closed without merging**
