### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Ramharsh-aidev**

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — APPROVED** [review]

**Comment by AKSHITHA-CHILUKA** [comment]
Can you provide your badge link?
The one you have mentioned in not the one we want so once provide the badge link

**Comment by Ramharsh-aidev** [comment]
Hello @AKSHITHA-CHILUKA 
I had give link in which my email Id is not present by selecting the option share without showing emial id 
image

you can see the ss of that website for confirming that I had completed the course

but I didn't received any point on the Gssoc leader board?? could you please help with that

**Comment by AKSHITHA-CHILUKA** [comment]
Click on the share button and send that link here
@Ramharsh-aidev

**Comment by AKSHITHA-CHILUKA** [comment]
image
I can see you ponits on the lb

**Comment by Ramharsh-aidev** [comment]
Oh ok I think it was not updated when I checked that 😅 
thanks 👍🏻

**Pull request merged**
