### PR TITLE
Update Certificate for Supriya Gorai

### PR DESCRIPTION
**Pull request by SupriyaGo**

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
image

you cannot remove like this

**Comment by SupriyaGo** [comment]
No, I did not remove it, I just copied line no 1211 and added one more line in  line no 1212 with my details. I don't know why it is showing in 1214. @AKSHITHA-CHILUKA

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr @SupriyaGo

**Comment by SupriyaGo** [comment]
image
Like this @AKSHITHA-CHILUKA

**Pull request closed without merging**
