### PR TITLE
Added Postman Challenge

### PR DESCRIPTION
**Pull request by SadafKausar2025**
hello @sanjay-kv 
please review this PR

### CODE REVIEW

**Review by Princegupta101 — APPROVED** [review]
Awesome you will be able to see your 500 points on next leaderboard server run,
let us know how much time you took to complete it.

**Comment by SadafKausar2025** [comment]
> Awesome you will be able to see your 500 points on next leaderboard server run, let us know how much time you took to complete it.

Thank you @Princegupta101

**Comment by SadafKausar2025** [comment]
> > Awesome you will be able to see your 500 points on next leaderboard server run, let us know how much time you took to complete it.
> 
> Thank you @Princegupta101

To complete the postman challenge I took 1 hour to complete

**Comment by SadafKausar2025** [comment]
hello @Princegupta101  
please check this Postman Pr is not included in my leaderboard

**Comment by sanjay-kv** [comment]
we are fixing it, its taking more than usual time we know. the bug is been bit tricky to find out

**Comment by SadafKausar2025** [comment]
Sharing the Linkedin Post in My PR here:
Linkedin post : https://www.linkedin.com/feed/update/urn:li:activity:7223244498565255168/
mail Id : sadafkausar2003@gmail.com

**Pull request merged**
