### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by AsifQamar**
added my certificate

### CODE REVIEW

**Comment by AsifQamar** [comment]
@AKSHITHA-CHILUKA review and merge it please

**Comment by AKSHITHA-CHILUKA** [comment]
you have removed others details so I cannot merge it 
please open a new pr just by adding your details , do not change anything else
image

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr @AsifQamar

**Comment by AsifQamar** [comment]
ok

**Pull request closed without merging**
