### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by ManaGit7**
Added my name.

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
open a new pr and just add your details and do not changes others details @ManaGit7

**Comment by ManaGit7** [comment]
Done Ma'am. It shows no conflicts now.

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr

**Comment by ManaGit7** [comment]
Done👍

**Pull request closed without merging**
