### PR TITLE
Certificate Completion - Nishil Pathak

### PR DESCRIPTION
**Pull request by nishil61**
Please review it and merge!!

### CODE REVIEW

**Comment by nishil61** [comment]
@sanjay-kv @NIKHIL0VERMA @jindalpriyanshu101 @SAM-DEV007 Please review and merge!

**Comment by jindalpriyanshu101** [comment]
Well I'm not the maintainer. but, resolve your merge conflicts.

**Comment by nishil61** [comment]
@jindalpriyanshu101 Done with resolving.

**Comment by sanjay-kv** [comment]
hi you need to raise the new PR, your conflict resolve affected other people data

**Pull request closed without merging**
