### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by sumitsingh24k**
added my postman cert

### CODE REVIEW

**Review by Adibakhan14 — APPROVED** [review]

**Comment by vivekvardhan2810** [comment]
@sumitsingh24k please close this PR, as your recent PR was merged.

**Comment by vivekvardhan2810** [comment]
@shreyash3087 please close this PR, as you have recently merged one of his PR.

**Comment by vivekvardhan2810** [comment]
@sumitsingh24k please close this PR.

**Comment by vivekvardhan2810** [comment]
@shreyash3087 please close this PR, as you have recently merged one of his PR.

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA please close this PR.

**Pull request closed without merging**
