### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Dipika005**
Added my badge

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
image

is your name krish patel @Dipika005

**Comment by AKSHITHA-CHILUKA** [comment]
Please do the necessary changes again do not copy

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr I will be closing this for now

**Comment by Dipika005** [comment]
how do i correct it?

**Comment by Dipika005** [comment]
how do i correct it?

**Comment by AKSHITHA-CHILUKA** [comment]
open a new pr @Dipika005

**Comment by Dipika005** [comment]
Done. but not showing merge option

**Pull request closed without merging**
