### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by DarakshanSaara**
added my name

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@DarakshanSaara you have already a merged PR previously, then why have you created a new PR.

your previous PR was merged.

and we can see the postman points of yours on the leaderboard.

please check it.

and please close the PR.

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA PLEASE CLOSE THIS PR.

**Comment by DarakshanSaara** [comment]
Okay, I wasn't aware before

**Comment by vivekvardhan2810** [comment]
@DarakshanSaara No problem.

**Pull request closed without merging**
