### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Soumyadeeep-Mukherjee**
Soumyadeep Mukherjee

### CODE REVIEW

**Comment by vivekvardhan2810** [comment]
@Soumyadeeep-Mukherjee please close this PR, as one your PR was merged before.

**Comment by vivekvardhan2810** [comment]
@Soumyadeeep-Mukherjee why are you creating the PR again, your previous PR was merged.

please close this PR.

**Comment by Soumyadeeep-Mukherjee** [comment]
The link is not working in that one

**Comment by Soumyadeeep-Mukherjee** [comment]
> @Soumyadeeep-Mukherjee please close this PR, as one your PR was merged before.

the previous PR Link is not active, so i edited the previous PR, sorry for the inconvinience

**Comment by Soumyadeeep-Mukherjee** [comment]
The PR will be merged right ? As the previous one was not working

**Comment by vivekvardhan2810** [comment]
@Soumyadeeep-Mukherjee it will be done.

the team will look into this.

please understand.

**Comment by aslams2020** [comment]
Merged #3617 
NO need to do anything. You'll get the points in the next lb updates.

**Comment by Soumyadeeep-Mukherjee** [comment]
> Merged #3617 NO need to do anything. You'll get the points in the next lb updates.

where will i find my name in the repo,cant find

**Comment by vivekvardhan2810** [comment]
@Soumyadeeep-Mukherjee 

here is your name in repo

image

**Comment by Soumyadeeep-Mukherjee** [comment]
> @Soumyadeeep-Mukherjee
> 
> here is your name in repo
> 
> image
> 
> i hope your query was resolved and cleared.

But here the links are not active (in that entry) , thats why i made a new entry with the links properly, in that new PR. as i said earlier, please look into this and tell me what to do. That edited new PR entry as cancelled ( with the edited active links ). i hope i am making myself clear, please guide me, i am stuck from yesterday. thank you....

**Comment by vivekvardhan2810** [comment]
@aslams2020 please look into this issue.

**Comment by aslams2020** [comment]
@Soumyadeeep-Mukherjee Ok, Sorry for the oversight

You could've mentioned in the description that you are updating some info. 
As there are many PR coming up -- it happens.

**Comment by aslams2020** [comment]
@Soumyadeeep-Mukherjee Done

**Comment by Soumyadeeep-Mukherjee** [comment]
Thank you! Its showing now with the working link.

**Pull request merged**
