### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Mohan-Murali-02**
added my details

### CODE REVIEW

**Review by aslams2020 — APPROVED** [review]

**Review by aslams2020 — COMMENTED** [review]
Congratulations for your certification! your scores will get reflected in next server update! ⚡

**Comment by Mohan-Murali-02** [comment]
Thank you, Do I need to download any certificate or what??

**Comment by aslams2020** [comment]
No, you got 500 points on the leaderboard

**Comment by Mohan-Murali-02** [comment]
Ok, thanks for the clarification.

**Pull request merged**
