### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by saimohan11**
added my name

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
please add your details at the end and donot change others details

**Comment by saimohan11** [comment]
@AKSHITHA-CHILUKA what I need to do I didn't get what you are saying.

**Comment by AKSHITHA-CHILUKA** [comment]
image
Please open an other pr and add your details again @saimohan11

**Comment by saimohan11** [comment]
I need to remove the old details and I need to add new details of mine.

**Comment by vivekvardhan2810** [comment]
@saimohan11 you don't need to remove older entries.

just add your details at the bottom.

and close this pull request.

for example it should be like this without disturbing the other one's

image

**Comment by saimohan11** [comment]
Ok, I will do it.

**Pull request closed without merging**
