### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by AKA-5**
Kaleem Akhtar

### CODE REVIEW

**Review by Ravi-1606 — CHANGES_REQUESTED** [review]
Please change your s.no. 2596 is already taken by someone else

**Review by Mayank-joshi-21 — CHANGES_REQUESTED** [review]
Please change your serial number 2596 is my serial number otherwise you will get a conflict.

**Comment by AKA-5** [comment]
@sanjay-kv @MastanSayyad  kindly help me add my certification in this file I am having conflicts again and again

**Review by MastanSayyad — COMMENTED** [review]
@AKA-5 create a new PR and add your name at the last bottom and tag me

**Pull request closed without merging**
