### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by Mani1881**
final added certificate

### CODE REVIEW

**Review by AKSHITHA-CHILUKA — CHANGES_REQUESTED** [review]
open a new pr @Mani1881

**Comment by Mani1881** [comment]
added final pr i changed it according due to arsing of resolving conflicts

**Comment by aslams2020** [comment]
@Mani1881 That will be merged soon.

**Comment by Mani1881** [comment]
Ok, I will wait. Thanks

**Pull request closed without merging**
