### PR TITLE
Update add-your-certificate.md

### PR DESCRIPTION
**Pull request by zalabhavy**
@sanjay-kv Done Please check it now !

Thank You !

### CODE REVIEW

**Comment by zalabhavy** [comment]
@Princegupta101 Can You Please check it !

Thank You !

**Review by Princegupta101 — APPROVED** [review]
hey, we have issue in merging your PR, could you raise the PR again. Sorry for the trouble.

**Comment by zalabhavy** [comment]
@Princegupta101 Yes please check it i will make it right now !

**Comment by zalabhavy** [comment]
@Princegupta101 It is solved ?

**Pull request merged**
